### ISSUE TITLE
Fabric Post Processor Fails to run 

### ISSUE THREAD

**Issue by yasmin-asar** [AndrewPMeade/FabricPostProcessor#1]
Hi, 

I am using the FabricPostProcessor on BayesTraits output (after using the Fabric model). My tree has 3,366 taxa, with the MCMC run for 500,000,000 generations + stepping stone sampling. When I use the FabricPostProcessor to get a CSV file with the numbers of significant betas and scalars, I receive this error message:

"Traceback (most recent call last):
  File "FabricPostProcessor.py", line 347, in <module>
  File "FabricPostProcessor.py", line 342, in main
  File "FabricPostProcessor.py", line 301, in CreateData
  File "FabricPostProcessor.py", line 120, in OutputSclars
  File "FabricPostProcessor.py", line 58, in GetParameterSignificance
ValueError: math domain error
[37178] Failed to execute script 'FabricPostProcessor' due to unhandled exception!"

Please note that I have used the FabricPostProcessor the marsupials example as well as for a number of smaller pilot studies with no issues at all. Could you please help me fix this?

Thanks,
Yasmin

**Comment by AndrewPMeade** [comment]
Hi Yasmin,
                Sorry about that, can you please send me the files you sued to run it and I will take a look.

                Thanks andrew.

From: yasmin-asar ***@***.***>
Sent: Wednesday, May 31, 2023 12:46 AM
To: AndrewPMeade/FabricPostProcessor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndrewPMeade/FabricPostProcessor] Fabric Post Processor Fails to run (Issue #1)


Hi,

I am using the FabricPostProcessor on BayesTraits output (after using the Fabric model). My tree has 3,366 taxa, with the MCMC run for 500,000,000 generations + stepping stone sampling. When I use the FabricPostProcessor to get a CSV file with the numbers of significant betas and scalars, I receive this error message:

"Traceback (most recent call last):
File "FabricPostProcessor.py", line 347, in
File "FabricPostProcessor.py", line 342, in main
File "FabricPostProcessor.py", line 301, in CreateData
File "FabricPostProcessor.py", line 120, in OutputSclars
File "FabricPostProcessor.py", line 58, in GetParameterSignificance
ValueError: math domain error
[37178] Failed to execute script 'FabricPostProcessor' due to unhandled exception!"

Please note that I have used the FabricPostProcessor the marsupials example as well as for a number of smaller pilot studies with no issues at all. Could you please help me fix this!

Thanks,
Yasmin

-

**Comment by yasmin-asar** [comment]
Hi Andrew, 

Thank you for your swift response, I have emailed you the tree, .VarRates.txt. and  .log.txt files. 

Best,
Yasmin
